name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # https://github.com/actions/setup-node/
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.6'
    - run: npm install
    - run: npm run build
    - run: npm run export
    # https://github.com/peaceiris/actions-gh-pages
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./out
        cname: www.abouthouseplants.com
